### ISSUE TITLE
Interactive nodes

### ISSUE THREAD

**Issue by zachmanpro** [Patcher56/vue-flowy#1]
Hi Patric

I was wondering what the simplest way is to make to the nodes interactive, for example, clicking on a node opens a dialogue?

Also maybe an option to make it top down instead of left to right

**Comment by p-kuen** [comment]
Hi,
I will check that as soon as possible.

**Comment by AdamBissonnette** [comment]
Any updates on this? You seem to have the best clean / straightforward uml chart builder I've found for vue so far. Top down rendering and interactive nodes would be awesome!
