### ISSUE TITLE
Nodes remains saved after destruction

### ISSUE THREAD

**Issue by matveyson** [Patcher56/vue-flowy#3]
**Problem:** After creating a new instance of FlowChart and adding elements to it I've experienced `'ID ' + this.id + 'is already registered!'` error.

**My Research:** It seems to me that flowElementsById (FlowElement.js:1 | FlowElement.d.ts:13) remembers old elements due to ES6 imports singleton effect.

Is it a bug or just a consequence of inappropriate library usage? If so, what should I do, if I need to have FlowChart with element_ids that were used before:

**Steps To Reproduce:**
1. Draw FlowChart with elements [12, 13, 14, 15];
2. Leave Page -> Go to new Page;
3. Draw FlowChart with elements [12, 19, 20, 21];

**Comment by p-kuen** [comment]
This should be fixed with f0b7277cc83e4e042f8f0ada50961f5e38e02b96 thanks to @pulzzejason 
You can now use `<FlowChart>.destroy()` to clear all items.
